<?php

define('ISLANDORA_BATCH_STATE__NOT_READY', 0);
define('ISLANDORA_BATCH_STATE__READY', 1);
define('ISLANDORA_BATCH_STATE__PENDING_CHILDREN', 2);
define('ISLANDORA_BATCH_STATE__DONE', 3);

function islandora_batch_handle_preprocessor(IslandoraBatchPreprocessor $preprocessor) {
  return $preprocessor->preprocess();
}

/**
 * Generate and set the batch operations.
 *
 * After calling this, it will be necessary to call one of the functions which
 * actually execute the batch, such as batch_process(),
 * drush_backend_batch_process() or background_batch_process_batch().
 *
 * Queries the database for preprocessed entries, and attempts to ingest them.
 */
function islandora_batch_set_operations (array $parameters) {
  $batch = array(
    'title' => t('Islandora Batch Ingest'),
    'finished' => 'islandora_batch_finished',
    'init_message' => t('Initializing...'),
    'file' => drupal_get_path('module', 'islandora_batch') . '/includes/ingest.batch.inc',
    'operations' => array(
      array('islandora_batch_ingest_process', array($parameters)),
    ),
  );

  batch_set($batch);
}

/**
 * "Dumbly" sets the batch operations and calls batch_process().
 */
function islandora_batch_ingest() {
  islandora_batch_set_operations();
  batch_process();
}
