<?php

/**
 * @file
 * Module for Batch ingest statistic tracking and reporting.
 */

/**
 * Implements hook_menu().
 */
function islandora_batch_report_menu() {
  $items = array();

  $items['admin/islandora/tools/batchreport'] = array(
    'title' => 'Islandora Batch Reporting Settings',
    'description' => 'Configure settings for Islandora Batch Reporting.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_batch_report_admin_form'),
    'file' => 'includes/admin.form.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_islandora_batch_object_processed().
 *
 * Log processed objects and sets into database.
 */
function islandora_batch_report_islandora_batch_object_processed($object, $state) {
  module_load_include('inc', 'islandora_batch_report', 'includes/db');
  module_load_include('inc', 'islandora_batch', 'includes/db');
  $content_models = $object->relationships->get(FEDORA_MODEL_URI, 'hasModel');
  $content_model = (isset($content_models[0]['object']['value']) ? $content_models[0]['object']['value'] : '');

  // Log object details in database.
  islandora_batch_report_log_object($object, $content_model, $state);
  db_insert('islandora_batch_report_objects_processed')->fields(array(
    'pid' => $object->id,
    'contentmodel' => $content_model,
    'label' => $object->label,
    'successful' => (int) $state,
    'timestamp' => REQUEST_TIME,
  ))->execute();

  // Batch ingest can process outside of a specific set so it needs to check
  // the set from each object and update the database accordingly.
  $set_id = islandora_batch_get_set_for_object($object->id);
  // Check the set status.
  $set_failed = islandora_batch_check_if_set_failed_ingest($set_id);
  $set_ingested = islandora_batch_check_if_set_is_fully_ingested($set_id);
  if ($set_failed || $set_ingested) {
    if ($set_failed) {
      $set_status = 0;
    }
    else {
      $set_status = 1;
    }
    // See if it already exists in the table within the day and has the same
    // processing status.
    $set_exists_in_database = islandora_batch_report_check_if_set_was_added($set_id, $set_status);
    if (!$set_exists_in_database) {
      // Log set details in database.
      islandora_batch_report_log_set($set_id, $set_status);
    }
  }
}

/**
 * Implements hook_mail().
 */
function islandora_batch_report_mail($key, &$message, $params) {
  switch ($key) {
    case 'daily_batch_ingest_report':
      module_load_include('inc', 'islandora_batch_report', 'includes/db');
      module_load_include('inc', 'islandora_batch', 'includes/db');
      $timestamp = time();
      // Build subject and body.
      $message['subject'] = t('Daily Islandora Batch Ingest Report - @date',
        array('@date' => date('m/d/Y', $timestamp))
      );

      $message['body'][] = t("On @date, @object_count objects were ingested:\n\n@content_model_counts\n @successful_set_count Sets were successfully processed.\n @failed_set_count Sets were unsuccessfully processed.\n\n There are still:\n\n @current_set_queue_count Sets that remain to be processed.\n @current_object_queue_count Objects that remain to be ingested.",
        array(
          '@date' => date('M jS', $timestamp),
          '@object_count' => islandora_batch_report_get_daily_object_count(1, $timestamp),
          '@content_model_counts' => islandora_batch_report_get_daily_object_count_by_content_model(1, $timestamp),
          '@successful_set_count' => islandora_batch_report_get_daily_set_count(1, $timestamp),
          '@failed_set_count' => islandora_batch_report_get_daily_set_count(0, $timestamp),
          '@current_set_queue_count' => islandora_batch_get_count_of_queued_sets_ready_to_process(),
          '@current_object_queue_count' => islandora_batch_get_count_of_queued_objects_ready_to_process(),
        )
      );
      break;
  }
}
